# Generated by Django 5.2.4 on 2026-03-24 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('microcontroller', 'Microcontroller'), ('sensor', 'Sensor'), ('actuator', 'Actuator'), ('module', 'Module'), ('display', 'Display'), ('power', 'Power'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.TextField(help_text="Comma-separated keywords for matching (e.g., 'arduino, uno, atmega328')")),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=15)),
                ('instructions', models.TextField(blank=True, help_text='Brief build instructions or tips')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=4)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='robohelper.chatsession')),
                ('matched_components', models.ManyToManyField(blank=True, to='robohelper.component')),
                ('suggested_projects', models.ManyToManyField(blank=True, to='robohelper.project')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robohelper.component')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robohelper.project')),
            ],
            options={
                'unique_together': {('project', 'component')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='components',
            field=models.ManyToManyField(through='robohelper.ProjectComponent', to='robohelper.component'),
        ),
    ]
